### ISSUE TITLE
Audio playback error for widget StoryItemType.text in WEB

### ISSUE THREAD

**Issue by nmakarychev** [devkrest/flutter_story_presenter#14]
Hello
Audio playback error for widget StoryItemType.text in WEB

`DartError: AnimationController.forward() called with no default duration.
The "duration" property should be set, either in the constructor or later, before calling the forward() function.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3  throw_
errors.dart:296
packages/flutter/src/animation/animation_controller.dart 483:9               <fn>
animation_controller.dart:483
packages/flutter/src/animation/animation_controller.dart 489:14              forward
animation_controller.dart:489
packages/flutter_story_presenter/src/story_presenter/story_view.dart 251:9   <fn>
story_view.dart:251
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
zone.dart:1661
dart-sdk/lib/async/future_impl.dart 163:18                                   handleValue
future_impl.dart:163
dart-sdk/lib/async/future_impl.dart 861:44                                   handleValueCallback
future_impl.dart:861
dart-sdk/lib/async/future_impl.dart 890:13                                   _propagateToListeners
future_impl.dart:890
dart-sdk/lib/async/future_impl.dart 472:9                                    callback
future_impl.dart:472
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
schedule_microtask.dart:40
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
schedule_microtask.dart:49
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>
async_patch.dart:181
DartError: AnimationController.forward() called with no default duration.
The "duration" property should be set, either in the constructor or later, before calling the forward() function.
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3  throw_
errors.dart:296
packages/flutter/src/animation/animation_controller.dart 483:9               <fn>
animation_controller.dart:483
packages/flutter/src/animation/animation_controller.dart 489:14              forward
animation_controller.dart:489
packages/flutter_story_presenter/src/story_presenter/story_view.dart 224:29  [_resumeMedia]
story_view.dart:224
packages/flutter_story_presenter/src/story_presenter/story_view.dart 263:15  <fn>
story_view.dart:263
dart-sdk/lib/async/zone.dart 1594:9                                          runUnaryGuarded
zone.dart:1594
dart-sdk/lib/async/stream_impl.dart 365:5                                    [_sendData]
stream_impl.dart:365
dart-sdk/lib/async/stream_impl.dart 297:7                                    [_add]
stream_impl.dart:297
dart-sdk/lib/async/stream_impl.dart 1127:36                                  addSync
stream_impl.dart:1127
packages/rxdart/src/utils/forwarding_stream.dart 130:35                      add
forwarding_stream.dart:130
packages/rxdart/src/transformers/start_with.dart 12:31                       onData
start_with.dart:12
dart-sdk/lib/async/zone.dart 1594:9                                          runUnaryGuarded
zone.dart:1594
dart-sdk/lib/async/stream_impl.dart 365:5                                    [_sendData]
stream_impl.dart:365
dart-sdk/lib/async/stream_impl.dart 541:13                                   perform
stream_impl.dart:541
dart-sdk/lib/async/stream_impl.dart 646:10                                   handleNext
stream_impl.dart:646
dart-sdk/lib/async/stream_impl.dart 617:7                                    callback
stream_impl.dart:617
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
schedule_microtask.dart:40
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
schedule_microtask.dart:49
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>
async_patch.dart:181
[log] STATE ==> AppLifecycleState.inactive
`

**Comment by Kaival-Patel** [comment]
Thanks for reporting the issue, but currently we are not providing support for Flutter WEB. We are planning soon to roll out an update for the Flutter Web.
