### ISSUE TITLE
Header and Footer widget for StoryItem?

### ISSUE THREAD

**Issue by AlcoholicCoder** [devkrest/flutter_story_presenter#15]
Please allow setting custom `header` and `footer` widget for each `StoryItem` rather than footer for `FlutterStoryView`.

**Comment by AlcoholicCoder** [comment]
I've tried but `footerWidget` doesn't get rebuilt on `index` change.
```
footerWidget: Builder(builder: (context) {
        Uri? uri = widget.story.status[controller.storyStatus.index].link;
        if (uri != null) {
          return ElevatedButton(
            onPressed: () {
              print("Click registered");
            },
            child: const Text("Click me"),
          );
        }
        return const SizedBox.shrink();
      }),
```

**Comment by Kaival-Patel** [comment]
@AlcoholicCoder Thanks for raising the issue and shredding light on vital functionality that's having issues. We would soon check this and resolve it.

**Comment by AlcoholicCoder** [comment]
> @AlcoholicCoder Thanks for raising the issue and shredding light on vital functionality that's having issues. We would soon check this and resolve it.

Thank you for this awesome library I've used `ValueNotifier` to solve this issue. Works fine.
