### ISSUE TITLE
State Preservation Issue After Switching User Stories

### ISSUE THREAD

**Issue by 2001arman** [devkrest/flutter_story_presenter#17]
Hi @devkrest, great package! I have a request regarding the state after changing user stories. For example, if I have two user stories, and I’ve already viewed the third story in the first user story, when I slide to the second user story and then return to the first, the index resets to 0 (or the first story). Could you please fix this using state management so that the viewed index is preserved? Thanks!

**Comment by Kaival-Patel** [comment]
Hello, @2001arman. The issue you have mentioned is not part of the plugin and it is the example stating you can achieve the functionality of Instagram or any other popular social media. The state management should be ✅ by the user and the issue you are mentioning is just an example, not the actual package.

Closing as it is not related to the package.
