### ISSUE TITLE
Error: Video Controller was used after disposed

### ISSUE THREAD

**Issue by whatsevr** [devkrest/flutter_story_presenter#20]

**Comment by Kaival-Patel** [comment]
Please provide proper steps to reproduce and issue in depth to examine the problem and fix it.

**Comment by Kaival-Patel** [comment]
@whatsevr Please provide steps to reproduce. Thanks

**Comment by whatsevr** [comment]
Use pageview builder and a few story with Images and video from Cloud and fast scroll or fast swipe you will get the error on debug mode. Sorry i cannot share the code as of busy schedule.
