### ISSUE TITLE
Need cache extent count or preload count on Story View to preload images and video for better load experience

### ISSUE THREAD

**Issue by whatsevr** [devkrest/flutter_story_presenter#21]

**Comment by harshlet** [comment]
@whatsevr 
To preload image and video handling, we use the cached_network_image plugin, which integrates with flutter_cache_manager. Additionally, we utilize flutter_cache_manager directly for video caching, ensuring efficient resource management. By leveraging these tools, you can preload both images and videos, enhancing the overall performance and user experience in the app, while minimizing load times and data usage.

**Comment by harshlet** [comment]
@whatsevr 
To preload image and video handling, we use the cached_network_image plugin, which integrates with flutter_cache_manager. Additionally, we utilize flutter_cache_manager directly for video caching, ensuring efficient resource management. By leveraging these tools, you can preload both images and videos, enhancing the overall performance and user experience in the app, while minimizing load times and data usage.
