### ISSUE TITLE
SetState unpauses the FlutterStoryController

### ISSUE THREAD

**Issue by AmauryTejada** [devkrest/flutter_story_presenter#22]
Hi @devkrest ,

Thank you for creating this package. It has significantly sped up the development of a story-like feature in my company's app. However, we're currently facing an issue with state management. Whenever the controller is paused and we perform a SetState or any action that forces a redraw, it starts playing immediately, which is not ideal for our use case.

Is this behavior intended? Are we missing something, or is it actually a bug? I've attached a small example that replicates this behavior.

We would greatly appreciate your help.

Best regards,

```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_story_presenter/flutter_story_presenter.dart';

class TestStories extends StatefulWidget {
  const TestStories({super.key});

  @override
  State<TestStories> createState() => _TestStoriesState();
}

class _TestStoriesState extends State<TestStories> {
  late final FlutterStoryController _controller;
  late final List<StoryItem> _stories;
  final Color paradisePink = const Color(0xFFE64467);

  @override
  void initState() {
    _controller = FlutterStoryController();
    _stories = [
      StoryItem(storyItemType: StoryItemType.text, url: "Hello World"),
    ];
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return FlutterStoryView(
      key: Key('Test-Stories'),
      restartOnCompleted: false,
      flutterStoryController: _controller,
      items: _stories,
      onStoryChanged: (int index) {
        print('~CHANGE');
      },
      footerWidget: TextButton(
        onPressed: () {
          HapticFeedback.lightImpact();
          _controller.pause();
          setState(() {});
        },
        child: Text('data'),
      ),
      storyViewIndicatorConfig: StoryViewIndicatorConfig(
        activeColor: paradisePink,
        backgroundCompletedColor: paradisePink,
      ),
    );
  }
}
```

**Comment by devkrest** [comment]
Hi @AmauryTejada 

Thanks for your feedback! We've identified the issue with the controller resuming playback on redraw and will work on a fix ASAP.

Best regards,
Devkrest Team

**Comment by Kaival-Patel** [comment]
Hi @AmauryTejada. Checking this soon.

**Comment by Kaival-Patel** [comment]
Hi @AmauryTejada. The issue is fixed. Can you please check running this branch? If everything looks good, we can merge to master. Thanks
https://github.com/devkrest/flutter_story_presenter/tree/fix/22-setState-unpauses-flutterstorycontroller

**Comment by AmauryTejada** [comment]
Hi @Kaival-Patel ,

I just tested the branch, and it works perfectly. Thank you very much for your quick response. Do you plan to merge this fix into the Master branch soon?

**Comment by Kaival-Patel** [comment]
Yeah, we will merge the branch into the `master` before Diwali. Happy Diwali 🪔 @AmauryTejada

**Comment by AmauryTejada** [comment]
Hi everyone!

I hope you're all doing well. I was wondering if there's any chance we could get this fix into the master branch soon? Thanks a lot!

**Comment by Kaival-Patel** [comment]
@AmauryTejada Already moved to master branch if you can test.
