### ISSUE TITLE
story time issue

### ISSUE THREAD

**Issue by hasuwebforest** [devkrest/flutter_story_presenter#29]
On header section, there is user having multiple story on different time but not able to update  individual story time. its take same time for all story.

please update code story wise time.

**Comment by harshlet** [comment]
@hasuwebforest 

You can set individual story **durations** dynamically instead of applying the same duration to all stories. Here's how you can set the duration for each story item explicitly

You can pass a Duration to each StoryItem directly when creating the story list:

```
final storyItems = [
  StoryItem(
    storyItemType: StoryItemType.image,
    **duration: Duration(seconds: 5),** // Duration for the first story
    url: "https://images.pexels.com/photos/3225517/pexels-photo-3225517.jpeg?auto=compress&cs=tinysrgb&w=800",
  ),
  StoryItem(
    storyItemType: StoryItemType.image,
    **duration: Duration(seconds: 30),** // Duration for the second story
    url: "https://images.pexels.com/photos/3225517/pexels-photo-3225517.jpeg?auto=compress&cs=tinysrgb&w=800",
  ),
];

```

**Comment by hasuwebforest** [comment]
Hi @harshlet 
i am not asking about duration.
i am asking about time of story when user had uploaded. 
user A having 3 story with diffrent time  like 1 at 7.00 AM another at 2.00 PM. and another at 6.30 PM.
Here it take 7.00 am for all. 
there is no way to update time of story when its change.
have you got this?

**Comment by harshlet** [comment]
@hasuwebforest 

The profile view is not part of the plugin but can be implemented using the onStoryChanged callback and headerWidget of FlutterStoryPresenter. 

The onStoryChanged callback lets you track the current story index, while the headerWidget allows you to customize the header, such as adding a profile image, username, or actions. 

Here's an example: dynamically update the profile image and name in headerWidget based on the current story index. In future updates, the FlutterStoryController will include a current index getter, simplifying this process further.

**Comment by hasuwebforest** [comment]
Thanks for reply. Happy Coding :)

**Comment by lastborncoltd** [comment]
> [@hasuwebforest](https://github.com/hasuwebforest)
> 
> The profile view is not part of the plugin but can be implemented using the onStoryChanged callback and headerWidget of FlutterStoryPresenter.
> 
> The onStoryChanged callback lets you track the current story index, while the headerWidget allows you to customize the header, such as adding a profile image, username, or actions.
> 
> Here's an example: dynamically update the profile image and name in headerWidget based on the current story index. In future updates, the FlutterStoryController will include a current index getter, simplifying this process further.

You did not add the example code. Please help, I need this.

**Comment by hasuwebforest** [comment]
> > [@hasuwebforest](https://github.com/hasuwebforest)
> > The profile view is not part of the plugin but can be implemented using the onStoryChanged callback and headerWidget of FlutterStoryPresenter.
> > The onStoryChanged callback lets you track the current story index, while the headerWidget allows you to customize the header, such as adding a profile image, username, or actions.
> > Here's an example: dynamically update the profile image and name in headerWidget based on the current story index. In future updates, the FlutterStoryController will include a current index getter, simplifying this process further.
> 
> You did not add the example code. Please help, I need this.

Hi @lastborncoltd i tried this library but not work as expectation. so i removed it.
