### ISSUE TITLE
Preload videos 

### ISSUE THREAD

**Issue by kameshkarthi** [devkrest/flutter_story_presenter#31]
Hello, Please add option to preload videos to reduce loading.

**Comment by harshlet** [comment]
@kameshkarthi 

To efficiently preload and cache videos, we directly use the flutter_cache_manager package. This approach ensures reduced load times, optimized resource usage, and a smoother user experience. we are internally using flutter_cache_manager plugin for caching you just have to preload the video with use of flutter_cache_manager then enable **cacheVideo** parameter in **StoryViewVideoConfig**

Here is example for preload video.

Step - 1 : To preload video you can use below code

`
import 'package:flutter_cache_manager/flutter_cache_manager.dart';

Future<void> preloadVideo(String videoUrl) async {
  final cacheManager = DefaultCacheManager();
  final response = await http.get(Uri.parse(videoUrl));

  if (response.statusCode == 200) {
    await cacheManager.putFile(
      videoUrl,
      response.bodyBytes,
      fileExtension: 'mp4',
    );
  }
}`

Step - 2 : After that you have to pass **true** to cacheVideo in **StoryViewVideoConfig**

```
 StoryItem(
          storyItemType: StoryItemType.video,
          storyItemSource: StoryItemSource.asset,
          url: 'assets/fb8512a35d6f4b2e8917b74a048de71a.MP4',
          thumbnail: const Center(
              child: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              CupertinoActivityIndicator(
                radius: 15,
              ),
              SizedBox(
                width: 10,
              ),
              Text('Video Loading')
            ],
          )),
          videoConfig: const **StoryViewVideoConfig**(
            fit: BoxFit.cover,
            cacheVideo: **true**
          ),
        )
```
