### ISSUE TITLE
enhancement

### ISSUE THREAD

**Issue by matran** [devkrest/flutter_story_presenter#32]
in storytype, image or video there is no title or caption. for example if you post photo you may need also to post text with it

**Comment by harshlet** [comment]
@matran 

You can implement it by yourself using footerWidget with onStoryChanged callback of FlutterStoryPresenter.

The onStoryChanged callback lets you track the current story index, while the headerWidget allows you to customize the footer, such as caption or any thing.

Here's an example: dynamically update the footerWidget based on the current story index. In future updates, the FlutterStoryController will include a current index getter, simplifying this process further.
