### ISSUE TITLE
issue if there is just 1 video story

### ISSUE THREAD

**Issue by aligurelli** [devkrest/flutter_story_presenter#6]
hi,

the app crashes if there is just 1 video story item. the storyItems must be just StoryItem(type:video) to replicate it.  having said that there must be no one more any other story. once the video story finish following crash occures:

`A VideoPlayerController was used after being disposed.
`

**Comment by Kaival-Patel** [comment]
Thanks for reporting @aligurelli. Let us investigate this issue and resolve this as soon as we can
